version: '3.8'
services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:version: '3.8'
  services:
    db:
      image: postgres:14
      environment:
        POSTGRES_DB: school_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
  
  volumes:
    postgres_data: